/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alee_ndktest_NdkTest */

#ifndef _Included_com_example_alee_ndktest_NdkTest
#define _Included_com_example_alee_ndktest_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alee_ndktest_NdkTest_getNativeString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getAnotherNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alee_ndktest_NdkTest_getAnotherNativeString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    setNativeString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_alee_ndktest_NdkTest_setNativeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getString
 * Signature: (Lcom/example/alee/ndktest/TestClass;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alee_ndktest_NdkTest_getString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    setString
 * Signature: (Lcom/example/alee/ndktest/TestClass;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_alee_ndktest_NdkTest_setString
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getInteger
 * Signature: (Lcom/example/alee/ndktest/TestClass;)I
 */
JNIEXPORT jint JNICALL Java_com_example_alee_ndktest_NdkTest_getInteger
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    setInteger
 * Signature: (Lcom/example/alee/ndktest/TestClass;I)V
 */
JNIEXPORT void JNICALL Java_com_example_alee_ndktest_NdkTest_setInteger
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getString2
 * Signature: (Lcom/example/alee/ndktest/TestClass;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alee_ndktest_NdkTest_getString2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    setString2
 * Signature: (Lcom/example/alee/ndktest/TestClass;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_alee_ndktest_NdkTest_setString2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    getInteger2
 * Signature: (Lcom/example/alee/ndktest/TestClass;)I
 */
JNIEXPORT jint JNICALL Java_com_example_alee_ndktest_NdkTest_getInteger2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_alee_ndktest_NdkTest
 * Method:    setInteger2
 * Signature: (Lcom/example/alee/ndktest/TestClass;I)V
 */
JNIEXPORT void JNICALL Java_com_example_alee_ndktest_NdkTest_setInteger2
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
